export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'
export const CHANGE_LOGIN_NAME = 'CHANGE_LOGIN_NAME'
export const CHANGE_LOGIN_ID = 'CHANGE_LOGIN_ID'
export const CHANGE_PASSWORD_DATA = 'CHANGE_PASSWORD_DATA'